name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Update package version
        run: |
          node -e "let pkg=require('./package.json'); \
            pkg.version += '.${{ github.run_number }}'; \
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"        

      - name: Read package version
        uses: jaywcjlove/github-action-package@main
        id: package

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ steps.package.outputs.version }}
          name: Release v${{ steps.package.outputs.version }}
          body: ${{ github.event.head_commit.message }}             