name: Publish to npm

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # only publish on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Get build number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
      
      - name: Update package version
        run: |
          node -e "let pkg=require('./package.json'); \
            pkg.version += '.${{ env.BUILD_NUMBER }}'; \
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"        

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
